### ISSUE TITLE
Count the number of links posted in the channel.

### ISSUE THREAD

**Issue by jakerothwell** [jakerothwell/Slack-Bot#4]
I added this as an issue because we can use this function as a way to evolve the bot based on the activity of the channel. We could use this function for counting gif images to enter the "meme" state, or count the number of links to enter the "informative" states.

**Comment by jakerothwell** [comment]
For now we can just count from the beginning of the channel's history, we can later update it to calculate frequency over an X time interval.

**Comment by agoshula1** [comment]
This will require using the Web API and/or Events API (instead of the RTM API which we have been using so far), which also requires handling HTTPS traffic from Slack. I have some ideas of how to make this work thanks to some tutorials I found, but I'm not sure how long it may take for me to get this to work. So I'm going to move on to another issue for now to get something else done for our report. 

*EDIT* As an alternative solution, will try getting Wit to detect a url
